### ISSUE TITLE
Not able to generate summary

### ISSUE THREAD

**Issue by Shubham04Sanap** [AnujK2901/yt-sum-flask#6] opened 2022-08-07 17:30 UTC
I checked your website n wasn't able to get any summary, why does it always say your vid. does not have enough subs to generate a summary?

![image](https://user-images.githubusercontent.com/81099588/183303465-812171ca-b66b-4f8b-b3bf-310b41453a25.png)

**Comment by AnujK2901** [comment] 2022-08-08 02:34
This is not an issue @Shubham04Sanap,
The tool checks for the video subtitles and if the subtitles are available, then it checks the number of sentences present in it first before processing. If the subtitles do not have punctuation, then how would someone recognize when a sentence is ending, and the next sentence is starting. That's why such videos are unfit for summarization even after having subtitles.
If you try any video having properly punctuated subtitles, the tool would work as intended.

Let me add some video links to test the tool if you are not able to get such videos. (Tip: Add filter while searching for videos with subtitles/closed captions. They are usually punctuated.)

https://youtu.be/XZmGGAbHqa0
https://youtu.be/kd33UVZhnAA
https://youtu.be/aqHhpahguVY

I have not tested these links, but hoping that they would work as intended since their subtitles are punctuated. So, let me know if these samples are fine.

Feel free to ask in more detail in case you are still having doubts.

**Comment by Shubham04Sanap** [comment] 2022-08-08 04:20
I know it wasn't an issue just wanted to comment. I understand it now. So, your code only works on subs with punctuation, I mistook it for generating scripts according to the timestamps for particular sentences.

**Comment by AnujK2901** [comment] 2022-08-08 04:22
Glad you have understood the logic.
I could have used timestamps, but still that would not be full-proof solution to know if the sentence has truly ended.

**Comment by AnujK2901** [comment] 2022-08-08 04:23
I would be closing the issue then.

**Closed by AnujK2901** 2022-08-08 04:23 UTC
Labels: wontfix

**Comment by Shubham04Sanap** [comment] 2022-08-08 04:29
I want to build a transcript sum chrome extension or a web app for videos with subs and if possible I would like to add sum for non-sub videos as well.
Anyways your project is impressive.Great man keep it up!

**Comment by AnujK2901** [comment] 2022-08-08 04:43
I have already a chrome extension based on tbus tool. Hope you make on your own as you intend to do.
